server:
  port: 8080
  servlet:
    context-path: /crudService

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.rabbitmq.exchange
    routingkeyCaso: crud.statistics.caso