server:
  port: 8080
  servlet:
    context-path: /crudService

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest

spring:
  application:
    name: CRUD-LV-SERVICE

crud:
  rabbitmq:
    exchange: crud.rabbitmq.exchange
    routingkeyCaso: crud.statistics.caso

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  